//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WsCliente
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", ConfigurationName="WsCliente.ZSD_ESTADO_CUENTA")]
    public interface ZSD_ESTADO_CUENTA
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:soap:functions:mc-style:ZSD_ESTADO_CUENTA:ZsdrfcEstadoCu" +
            "entaRequest", ReplyAction="urn:sap-com:document:sap:soap:functions:mc-style:ZSD_ESTADO_CUENTA:ZsdrfcEstadoCu" +
            "entaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WsCliente.ZsdrfcEstadoCuentaResponse1> ZsdrfcEstadoCuentaAsync(WsCliente.ZsdrfcEstadoCuentaRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZsdrfcEstadoCuenta
    {
        
        private string pKunnrField;
        
        private ZstrCabEstadoCuenta[] tCabField;
        
        private ZstrEstadoCuenta[] tDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string PKunnr
        {
            get
            {
                return this.pKunnrField;
            }
            set
            {
                this.pKunnrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZstrCabEstadoCuenta[] TCab
        {
            get
            {
                return this.tCabField;
            }
            set
            {
                this.tCabField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZstrEstadoCuenta[] TData
        {
            get
            {
                return this.tDataField;
            }
            set
            {
                this.tDataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZstrCabEstadoCuenta
    {
        
        private string kkberField;
        
        private string kkbtxField;
        
        private decimal klimkField;
        
        private string waersField;
        
        private decimal cmtotField;
        
        private string porcTField;
        
        private decimal saldoField;
        
        private string porcDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Kkber
        {
            get
            {
                return this.kkberField;
            }
            set
            {
                this.kkberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Kkbtx
        {
            get
            {
                return this.kkbtxField;
            }
            set
            {
                this.kkbtxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public decimal Klimk
        {
            get
            {
                return this.klimkField;
            }
            set
            {
                this.klimkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Waers
        {
            get
            {
                return this.waersField;
            }
            set
            {
                this.waersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public decimal Cmtot
        {
            get
            {
                return this.cmtotField;
            }
            set
            {
                this.cmtotField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string PorcT
        {
            get
            {
                return this.porcTField;
            }
            set
            {
                this.porcTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public decimal Saldo
        {
            get
            {
                return this.saldoField;
            }
            set
            {
                this.saldoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string PorcD
        {
            get
            {
                return this.porcDField;
            }
            set
            {
                this.porcDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZstrEstadoCuenta
    {
        
        private string ltextField;
        
        private string docSunatField;
        
        private string bldatField;
        
        private string zfbdtField;
        
        private string qdatrField;
        
        private decimal dmbtrField;
        
        private string waersField;
        
        private decimal sald2Field;
        
        private decimal detraField;
        
        private decimal percepField;
        
        private string vkorgField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Ltext
        {
            get
            {
                return this.ltextField;
            }
            set
            {
                this.ltextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string DocSunat
        {
            get
            {
                return this.docSunatField;
            }
            set
            {
                this.docSunatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Bldat
        {
            get
            {
                return this.bldatField;
            }
            set
            {
                this.bldatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Zfbdt
        {
            get
            {
                return this.zfbdtField;
            }
            set
            {
                this.zfbdtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Qdatr
        {
            get
            {
                return this.qdatrField;
            }
            set
            {
                this.qdatrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public decimal Dmbtr
        {
            get
            {
                return this.dmbtrField;
            }
            set
            {
                this.dmbtrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string Waers
        {
            get
            {
                return this.waersField;
            }
            set
            {
                this.waersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public decimal Sald2
        {
            get
            {
                return this.sald2Field;
            }
            set
            {
                this.sald2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public decimal Detra
        {
            get
            {
                return this.detraField;
            }
            set
            {
                this.detraField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public decimal Percep
        {
            get
            {
                return this.percepField;
            }
            set
            {
                this.percepField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string Vkorg
        {
            get
            {
                return this.vkorgField;
            }
            set
            {
                this.vkorgField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZsdrfcEstadoCuentaResponse
    {
        
        private string gvNameClienteField;
        
        private string gvRegionField;
        
        private string gvSucursalField;
        
        private decimal gvTotalSaldoField;
        
        private ZstrCabEstadoCuenta[] tCabField;
        
        private ZstrEstadoCuenta[] tDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string GvNameCliente
        {
            get
            {
                return this.gvNameClienteField;
            }
            set
            {
                this.gvNameClienteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string GvRegion
        {
            get
            {
                return this.gvRegionField;
            }
            set
            {
                this.gvRegionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string GvSucursal
        {
            get
            {
                return this.gvSucursalField;
            }
            set
            {
                this.gvSucursalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public decimal GvTotalSaldo
        {
            get
            {
                return this.gvTotalSaldoField;
            }
            set
            {
                this.gvTotalSaldoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZstrCabEstadoCuenta[] TCab
        {
            get
            {
                return this.tCabField;
            }
            set
            {
                this.tCabField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZstrEstadoCuenta[] TData
        {
            get
            {
                return this.tDataField;
            }
            set
            {
                this.tDataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZsdrfcEstadoCuentaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public WsCliente.ZsdrfcEstadoCuenta ZsdrfcEstadoCuenta;
        
        public ZsdrfcEstadoCuentaRequest()
        {
        }
        
        public ZsdrfcEstadoCuentaRequest(WsCliente.ZsdrfcEstadoCuenta ZsdrfcEstadoCuenta)
        {
            this.ZsdrfcEstadoCuenta = ZsdrfcEstadoCuenta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZsdrfcEstadoCuentaResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public WsCliente.ZsdrfcEstadoCuentaResponse ZsdrfcEstadoCuentaResponse;
        
        public ZsdrfcEstadoCuentaResponse1()
        {
        }
        
        public ZsdrfcEstadoCuentaResponse1(WsCliente.ZsdrfcEstadoCuentaResponse ZsdrfcEstadoCuentaResponse)
        {
            this.ZsdrfcEstadoCuentaResponse = ZsdrfcEstadoCuentaResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface ZSD_ESTADO_CUENTAChannel : WsCliente.ZSD_ESTADO_CUENTA, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class ZSD_ESTADO_CUENTAClient : System.ServiceModel.ClientBase<WsCliente.ZSD_ESTADO_CUENTA>, WsCliente.ZSD_ESTADO_CUENTA
    {
        
        public ZSD_ESTADO_CUENTAClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WsCliente.ZsdrfcEstadoCuentaResponse1> WsCliente.ZSD_ESTADO_CUENTA.ZsdrfcEstadoCuentaAsync(WsCliente.ZsdrfcEstadoCuentaRequest request)
        {
            return base.Channel.ZsdrfcEstadoCuentaAsync(request);
        }
        
        public System.Threading.Tasks.Task<WsCliente.ZsdrfcEstadoCuentaResponse1> ZsdrfcEstadoCuentaAsync(WsCliente.ZsdrfcEstadoCuenta ZsdrfcEstadoCuenta)
        {
            WsCliente.ZsdrfcEstadoCuentaRequest inValue = new WsCliente.ZsdrfcEstadoCuentaRequest();
            inValue.ZsdrfcEstadoCuenta = ZsdrfcEstadoCuenta;
            return ((WsCliente.ZSD_ESTADO_CUENTA)(this)).ZsdrfcEstadoCuentaAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
    }
}
